import type { Locale } from "@/lib/i18n/locale";

// Replace the explicitly marked image/brief placeholders when studio assets arrive.
const copy = {
  en: {
    objectsTitle: "Small objects. Distinct characters.",
    objectsIntro: "Artisan keycaps, collectible characters and custom objects shaped by the studio's visual language.",
    processIntro: "Ideas take shape through drawing, sculpting, prototypes and careful finishing.",
    principlesTitle: "Attention to form, material and character.",
    exploreTitle: "Find your next step.",
    contactIntro: "Explore the custom-object process and prepare the references that describe your idea.",
    prepareIntro: "Describe your idea in words and share links to visual references you have permission to use.",
    originTitle: "New name. The same creative hands.",
    origin: "Luminal Factory continues the work of Lazy Factory: small resin characters, sculpted details and objects made to be kept. Meowhe connects that earlier chapter with the studio's next direction.",
    imageNote: "Temporary product reference · replace with a photograph of the studio.",
    imageAlt: "Meowhe resin character, used as a temporary studio image reference",
    studioTitle: "Inside the studio",
    studioDraft: "Studio portrait and workshop photographs will be added here. For now, explore the character and colorway records that show the studio's visual language.",
    archive: "Explore the archive",
    briefsTitle: "Three starting points for a custom object.",
    briefsNote: "Illustrative briefs with existing product photographs. These are examples to discuss, not completed commissions or offers for sale.",
    briefLabel: "Illustrative brief",
    briefs: [
      { title: "A character with a new palette", text: "Explore a color direction for an existing sculpt, with a clear mood and a small set of reference colors." },
      { title: "A story told through a small object", text: "Start with a character or theme, then discuss silhouette, readable details and the intended display." },
      { title: "A restrained visual identity", text: "Discuss a monochrome or brand-led direction, balancing a recognizable identity with the studio's sculptural language." },
    ],
    guideTitle: "How to start your collection.",
    guideIntro: "Discover the character first, then check the current release information before deciding how to take part.",
    guideSteps: [
      { title: "Discover a colorway", text: "The Archive brings together photographs, character details and colorway stories." },
      { title: "Check the release", text: "The Raffle page shows published releases. Read each release's status, rules and participation window when available." },
      { title: "Read before joining", text: "Check the release-specific price, compatibility and delivery information. Viewing a page does not reserve an object." },
    ],
    raffle: "View published releases",
    support: "Care & support",
    about: "Meet the studio",
    supportIntro: "A starting point for looking after your object and finding release information.",
    draftLabel: "Content preview",
    draftNote: "General care copy is provisional. Release-specific care, shipping and contact details will be confirmed before the relevant release opens.",
    careTitle: "Looking after a small resin object",
    care: [
      { title: "Gentle handling", text: "Support the body of the object when handling it. Avoid pulling small sculpted details or forcing a keycap onto an incompatible switch." },
      { title: "Dust and storage", text: "Use a soft, dry cloth or brush for light dust. Keep the object away from direct heat and prolonged sunlight; follow any care instructions supplied with the release." },
      { title: "Compatibility", text: "Check the switch and fit information for the specific release before installation. Do not assume every sculpt uses the same mounting system." },
    ],
    shippingTitle: "Shipping & release questions",
    shipping: [
      { title: "Where are price and shipping details?", text: "They belong to the individual release. Destination coverage, charges and dispatch timing are awaiting confirmation; this page does not publish a shipping promise." },
      { title: "Is an archived colorway available?", text: "An Archive record documents a colorway. It does not by itself confirm current stock or that a new release is planned." },
      { title: "How do I discuss a custom object?", text: "The Commission page explains the scope and information to prepare. Use its inquiry form only when it is available." },
    ],
    contactTitle: "Contact the studio",
    contactNote: "A verified public support address and official social links will be added here. Please use the published release information for now; the Commission page remains the place for custom-object inquiries.",
    commission: "Explore custom work",
  },
  vi: {
    objectsTitle: "Vật thể nhỏ. Nhân vật có dấu ấn riêng.",
    objectsIntro: "Artisan keycap, nhân vật sưu tầm và vật thể đặt riêng mang ngôn ngữ tạo hình của xưởng.",
    processIntro: "Ý tưởng thành hình qua phác thảo, tạo hình 3D, mẫu thử và những bước hoàn thiện cẩn thận.",
    principlesTitle: "Chú tâm vào hình khối, chất liệu và nhân vật.",
    exploreTitle: "Chọn bước khám phá tiếp theo.",
    contactIntro: "Tìm hiểu quy trình đặt làm riêng và chuẩn bị những hình tham khảo giúp diễn đạt ý tưởng của bạn.",
    prepareIntro: "Mô tả ý tưởng bằng lời và chia sẻ đường dẫn tới hình tham khảo bạn có quyền sử dụng.",
    originTitle: "Tên mới. Vẫn những bàn tay sáng tạo ấy.",
    origin: "Luminal Factory tiếp nối hành trình của Lazy Factory: những nhân vật resin nhỏ, chi tiết được tạo hình và vật thể để lưu giữ. Meowhe kết nối chặng đường trước đây với hướng phát triển tiếp theo của xưởng.",
    imageNote: "Ảnh sản phẩm minh họa tạm · sẽ thay bằng ảnh xưởng.",
    imageAlt: "Nhân vật Meowhe resin, dùng làm ảnh minh họa tạm cho xưởng",
    studioTitle: "Bên trong xưởng",
    studioDraft: "Chân dung người làm và ảnh không gian xưởng sẽ được bổ sung tại đây. Trong lúc chờ, bạn có thể khám phá nhân vật và phối màu để hiểu ngôn ngữ tạo hình của Luminal.",
    archive: "Khám phá bộ sưu tập",
    briefsTitle: "Ba điểm bắt đầu cho một vật thể riêng.",
    briefsNote: "Ví dụ ý tưởng dùng ảnh sản phẩm hiện có. Đây là hướng để trao đổi, chưa phải dự án đặt làm đã hoàn thành hay sản phẩm đang bán.",
    briefLabel: "Ý tưởng minh họa",
    briefs: [
      { title: "Nhân vật với bảng màu mới", text: "Khám phá hướng màu cho một tạo hình có sẵn, bắt đầu từ cảm xúc và một nhóm màu tham khảo rõ ràng." },
      { title: "Câu chuyện trong một vật thể nhỏ", text: "Bắt đầu từ nhân vật hoặc chủ đề, rồi trao đổi về dáng tổng thể, chi tiết dễ đọc và cách trưng bày." },
      { title: "Dấu ấn thị giác tiết chế", text: "Trao đổi về hướng đơn sắc hoặc nhận diện thương hiệu, cân bằng dấu ấn riêng với ngôn ngữ tạo hình của xưởng." },
    ],
    guideTitle: "Bắt đầu bộ sưu tập của bạn.",
    guideIntro: "Khám phá nhân vật trước, rồi xem thông tin đợt phát hành để chọn cách tham gia phù hợp.",
    guideSteps: [
      { title: "Khám phá phối màu", text: "Trang Lưu trữ tập hợp ảnh, thông tin nhân vật và câu chuyện của từng phối màu." },
      { title: "Xem đợt phát hành", text: "Trang Raffle hiển thị những đợt đã công bố. Đọc trạng thái, quy tắc và thời gian tham gia khi có thông tin." },
      { title: "Đọc trước khi tham gia", text: "Kiểm tra giá, độ tương thích và thông tin giao hàng riêng của đợt phát hành. Xem trang không đồng nghĩa với giữ chỗ sản phẩm." },
    ],
    raffle: "Xem đợt phát hành đã công bố",
    support: "Chăm sóc & hỗ trợ",
    about: "Tìm hiểu xưởng",
    supportIntro: "Hướng dẫn ban đầu để chăm sóc vật thể và tìm thông tin đợt phát hành.",
    draftLabel: "Nội dung xem trước",
    draftNote: "Hướng dẫn chăm sóc chung đang là bản tạm. Thông tin chăm sóc, giao hàng và liên hệ riêng sẽ được xác nhận trước khi mở đợt phát hành tương ứng.",
    careTitle: "Chăm sóc vật thể resin nhỏ",
    care: [
      { title: "Cầm nhẹ nhàng", text: "Đỡ phần thân khi cầm vật thể. Tránh kéo các chi tiết nhỏ hoặc ép keycap vào switch không phù hợp." },
      { title: "Vệ sinh và bảo quản", text: "Dùng khăn hoặc cọ mềm, khô để phủi bụi nhẹ. Tránh nguồn nhiệt trực tiếp và nắng kéo dài; ưu tiên hướng dẫn chăm sóc đi kèm đợt phát hành." },
      { title: "Độ tương thích", text: "Kiểm tra thông tin switch và cách lắp của đúng đợt phát hành trước khi sử dụng. Không mặc định mọi tạo hình dùng cùng kiểu chân gắn." },
    ],
    shippingTitle: "Giao hàng & câu hỏi về phát hành",
    shipping: [
      { title: "Xem giá và giao hàng ở đâu?", text: "Thông tin nằm tại từng đợt phát hành. Khu vực giao, phí và lịch gửi đang chờ xác nhận; trang này chưa công bố cam kết giao hàng." },
      { title: "Phối màu trong Lưu trữ còn bán không?", text: "Hồ sơ Lưu trữ ghi lại một phối màu. Sự xuất hiện tại đây không xác nhận còn hàng hoặc sẽ có đợt phát hành mới." },
      { title: "Trao đổi về vật thể đặt riêng thế nào?", text: "Trang Đặt làm riêng giải thích phạm vi và thông tin cần chuẩn bị. Chỉ dùng biểu mẫu yêu cầu khi biểu mẫu đã mở." },
    ],
    contactTitle: "Liên hệ xưởng",
    contactNote: "Địa chỉ hỗ trợ công khai và các kênh mạng xã hội chính thức sẽ được bổ sung sau khi xác nhận. Hiện bạn có thể xem thông tin đã công bố ở từng đợt phát hành; yêu cầu vật thể riêng được hướng dẫn tại trang Đặt làm riêng.",
    commission: "Tìm hiểu đặt làm riêng",
  },
} as const;

export function getStudioCopy(locale: Locale) { return copy[locale]; }
